color: null
fieldLayouts:
  1cd7c8b9-c949-40c8-8453-674057b6de4b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-10T09:52:13+02:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ca89ee18-9bf4-474a-b35d-f6dfc6ecc31d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-10T09:52:13+02:00'
            elementCondition: null
            fieldUid: f37b0bab-9cb9-4695-b431-f05d5e3bd8da # Single Line Text
            handle: summary
            includeInCards: false
            instructions: null
            label: Summary
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ddce7571-b5f2-4af5-b66c-c4e81f09f7ba
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-10T09:52:13+02:00'
            elementCondition: null
            fieldUid: 86b9888e-ef59-4f68-8ece-9b7badf30277 # Multi Line Text
            handle: details
            includeInCards: true
            instructions: null
            label: Details
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a305660c-5e74-44ea-aea8-f9a72d717dd3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 60639214-06c0-40de-a090-133b1ee8c7ac
        userCondition: null
handle: accordionItem
hasTitleField: false
icon: list-tree
name: Item
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{summary}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
