color: blue
fieldLayouts:
  1f795f65-54f6-434b-8f69-55a8b48b47e5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: cf78badd-1d49-472b-9548-8d0e3e4dc996
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 17ebe26e-858c-47f1-99d0-d010214c0afc # Accordion Items
            handle: null
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6f3e41b0-afa0-42ee-bc0f-2f8fe5fbac34
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c50d9275-0953-45ba-89c0-57c1a6e197c1
        userCondition: null
handle: accordion
hasTitleField: false
icon: bars
name: Accordion
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
