color: blue
fieldLayouts:
  686e6f99-599c-4052-bc6c-546f7d255804:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-20T19:11:39+02:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4ecd8d70-fd37-4f4e-8daf-b07161aff7a6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-20T19:11:39+02:00'
            elementCondition: null
            fieldUid: 588a9069-dcb4-469d-9e37-fbdb2834d780 # Column Content
            handle: null
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1db2b4b0-756f-4cbc-bdb0-348ba1e3aa43
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e64e42c8-b5c0-4bde-93fb-f4e171b86aa7
        userCondition: null
handle: columnWrapperRight
hasTitleField: false
icon: null
name: 'Right Column'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: "{columnContent.count} block(s) {columnContent.type('heading').one.text} "
titleTranslationKeyFormat: null
titleTranslationMethod: site
