color: blue
fieldLayouts:
  b658bf4d-0b93-4d93-af7a-cf78a1a65e7a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-07T12:02:47+02:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: bb678dd7-70ec-4aad-ae8c-3c4e1fdc5487
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-07T12:02:47+02:00'
            elementCondition: null
            fieldUid: 588a9069-dcb4-469d-9e37-fbdb2834d780 # Column Content
            handle: null
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 81749b69-40ff-4d67-b554-79af6a6f5272
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ad352948-3cf0-4677-abbd-0ad66690ecc2
        userCondition: null
handle: columnWrapperLeft
hasTitleField: false
icon: null
name: 'Left Column'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{columnContent.count} block(s) {columnContent.type(''heading'').one.text} '
titleTranslationKeyFormat: null
titleTranslationMethod: site
