color: null
fieldLayouts:
  5cb02b03-714e-4c7a-aba3-ca228dc7dfeb:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-07T12:02:47+02:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4645c227-4ce9-4e09-9116-04c6d04f76a5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-07T12:02:47+02:00'
            elementCondition: null
            fieldUid: dfec43e9-1949-4be3-bcfa-eeb2f8511b91 # Email
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ab3c1e1d-4ff0-46dc-9b37-bf3712b8ebc3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-07T12:02:47+02:00'
            elementCondition: null
            fieldUid: 560e7c36-f763-440f-b9b5-1d87228bc6df # Untranslatable Short Text
            handle: telephone
            includeInCards: false
            instructions: null
            label: Telephone
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2fd58459-73e1-460c-91aa-7b6c795d6e9d
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-08-07T12:02:47+02:00'
            elementCondition: null
            fieldUid: 560e7c36-f763-440f-b9b5-1d87228bc6df # Untranslatable Short Text
            handle: telephoneMobile
            includeInCards: false
            instructions: null
            label: 'Telephone (Mobile)'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 44677dda-2543-4664-b155-cb950be323bc
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-08-07T12:02:47+02:00'
            elementCondition: null
            fieldUid: 9e49c3cc-51f3-4bc0-ab6a-ecde20fcb06c # Social Media
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8b995dbe-fee1-4a45-a16e-950be409ea6b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 05e7a617-fc4f-40e0-b2c5-fdced1aca373
        userCondition: null
handle: contactInfo
hasTitleField: false
icon: id-card
name: 'Contact Info'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
