color: null
fieldLayouts:
  ffd120fe-033e-4efa-bc7a-e0f592d91137:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-10T09:52:13+02:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0465c1d2-3fb8-41f5-85c8-8aa6ff7abe30
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-10T09:52:13+02:00'
            elementCondition: null
            fieldUid: abb455ba-032b-461d-9c8d-dca9ed3fc7bd # Image
            handle: null
            includeInCards: false
            instructions: 'This image will be expanded to fill the full width of the screen.'
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f75657c5-6414-4e36-bacf-0fa4483cabd7
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2024-08-10T09:52:13+02:00'
            elementCondition: null
            fieldUid: f37b0bab-9cb9-4695-b431-f05d5e3bd8da # Single Line Text
            handle: caption
            includeInCards: false
            instructions: null
            label: Caption
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0e326a2c-e957-488a-bb33-b3510c3e96de
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2024-08-10T09:52:13+02:00'
            elementCondition: null
            fieldUid: 93372f33-2be3-4f89-9466-9ac943a3ea17 # Toggle
            handle: darken
            includeInCards: false
            instructions: 'Darken the image to make text more readable.'
            label: Darken
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 372007c8-17c8-40ee-aaa3-f935dc16d859
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2024-08-10T09:52:13+02:00'
            elementCondition: null
            fieldUid: cc29043c-ee3c-4afa-b50a-48728bb71115 # Caption Tag
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ea633397-7868-4e0d-bf13-f857e55f3796
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: 926a2cdb-6466-407a-be89-0c678368a50d
        userCondition: null
handle: fullWidthImage
hasTitleField: false
icon: images
name: 'Full Width Image'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
