color: null
fieldLayouts:
  41e5d65a-c578-41e0-8470-21b000104054:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-12T09:45:42+02:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 70ec7785-d0ac-46bb-a6e4-d73f93cec2d5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-12T09:45:42+02:00'
            elementCondition: null
            fieldUid: f37b0bab-9cb9-4695-b431-f05d5e3bd8da # Single Line Text
            handle: text
            includeInCards: true
            instructions: null
            label: __blank__
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0e184b02-4930-42e6-a09e-9f586f916fde
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2024-09-12T09:45:42+02:00'
            elementCondition: null
            fieldUid: 5c400efe-2716-4221-a54a-4ebaf6a3c6cb # Heading Level
            handle: null
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fdcd6c78-b61f-4ad7-80cc-58b9e85b6e96
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: 7d31a66e-6de9-46b8-8336-1205bfe7bb56
        userCondition: null
handle: heading
hasTitleField: false
icon: text
name: Heading
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
