color: null
fieldLayouts:
  7401d309-e508-45cd-b5e8-a48f92283981:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-07T12:02:47+02:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4a31dadb-3ebe-4829-8236-2bfce7d72b5e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-07T12:02:47+02:00'
            elementCondition: null
            fieldUid: 1d65442c-c0b9-46f4-8518-9a6c53e21bc1 # Featured Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6000495f-d20c-4d59-adac-23d09575d4f0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-07T12:02:47+02:00'
            elementCondition: null
            fieldUid: 95f98672-9562-44a0-8639-92d2b55ceeb6 # Body Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0442fdbb-7778-4e08-8d02-e35a73e9e416
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6aacb145-186e-49b1-9bd2-baaa3327a8ba
        userCondition: null
handle: home
hasTitleField: true
icon: house
name: Home
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: language
