color: null
fieldLayouts:
  b96ba22c-1dc3-4984-9618-dba5bf9072e1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6d5ac798-5d08-42f6-8181-90302e17ceb1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: abb455ba-032b-461d-9c8d-dca9ed3fc7bd # Image
            handle: null
            includeInCards: false
            instructions: null
            label: Image
            providesThumbs: true
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 53b039bc-1e34-432c-adfd-6ebaa5e40260
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f37b0bab-9cb9-4695-b431-f05d5e3bd8da # Single Line Text
            handle: caption
            includeInCards: true
            instructions: null
            label: Caption
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 41f6dd0d-36f7-4c4b-b68b-fc9ce884b71f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 76e79da0-ac5e-42ef-b095-ff42e4ff2b28
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8ed4044d-89b6-4d6b-a8a3-e303f533263a # Style
            handle: imageStyle
            includeInCards: false
            instructions: null
            label: Style
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fc2dbe43-5774-4787-a8a6-a78db3a25d39
            userCondition: null
            warning: null
            width: 25
        name: Style
        uid: d6833d7a-7be5-4a49-bc05-4be59b0d9125
        userCondition: null
handle: image
hasTitleField: false
icon: image
name: Image
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
