color: null
fieldLayouts:
  3c0a4ae5-e759-4942-aa4e-c1737058ad0a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-12T09:45:42+02:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4e057a4a-237b-4fe7-9d2a-93c9a509b52d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-12T09:45:42+02:00'
            dismissible: true
            elementCondition: null
            style: tip
            tip: 'Paginated post cards will be inserted here.'
            type: craft\fieldlayoutelements\Tip
            uid: cdd60b12-4c1c-4f0a-9dd5-09d54e854a6a
            userCondition: null
        name: Inhalt
        uid: c1d81378-8365-4b0c-abf6-f2ded6662401
        userCondition: null
handle: postIndex
hasTitleField: true
icon: list-radio
name: 'Post Index'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: language
