color: null
fieldLayouts:
  e3e14fe2-2ad5-4293-98c3-dc21e4272700:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-12T09:35:29+02:00'
            elementCondition: null
            template: _cp/drafts
            type: craft\fieldlayoutelements\Template
            uid: d19755e0-eb25-4af4-9dd1-cbf29a2eeb68
            userCondition: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-12T09:35:29+02:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 174bd17b-9d69-405c-b8b0-5d1bf6df167a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-12T09:35:29+02:00'
            elementCondition: null
            fieldUid: f37b0bab-9cb9-4695-b431-f05d5e3bd8da # Single Line Text
            handle: subheading
            includeInCards: true
            instructions: null
            label: Subheading
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1531a738-286f-4853-91dd-d0b677d6b9d1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-12T09:35:29+02:00'
            elementCondition: null
            fieldUid: 1d65442c-c0b9-46f4-8518-9a6c53e21bc1 # Featured Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: true
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0bcdc5e3-aee1-418c-baf7-4913c1a9da66
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-09-12T09:35:29+02:00'
            elementCondition: null
            fieldUid: 2ac14555-67e9-455b-9337-b07a50478276 # Topics
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 30b48803-aeeb-45e5-bc65-dc3d7c08f223
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-09-12T09:35:29+02:00'
            elementCondition: null
            fieldUid: 95f98672-9562-44a0-8639-92d2b55ceeb6 # Body Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ed5bf3fe-47cf-4f2e-bfa1-80966b3e0ac2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 547c5e84-0a14-4cb1-8567-8b569135baef
        userCondition: null
handle: post
hasTitleField: true
icon: file
name: Post
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: language
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: language
