color: emerald
fieldLayouts:
  bde6c865-48ee-4415-9ac7-2ef82c0b9b2f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-05T08:28:19+02:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3bd488e7-e259-495d-94c6-7c255835294b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-05T08:28:19+02:00'
            elementCondition: null
            fieldUid: 560e7c36-f763-440f-b9b5-1d87228bc6df # Untranslatable Short Text
            handle: siteName
            includeInCards: false
            instructions: null
            label: 'Site Name'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 31750ba7-c9dc-4f0d-bacf-bb6271e4fcec
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-05T08:28:19+02:00'
            elementCondition: null
            fieldUid: 560e7c36-f763-440f-b9b5-1d87228bc6df # Untranslatable Short Text
            handle: copyright
            includeInCards: true
            instructions: null
            label: Copyright
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6e118f46-8419-4f4a-894a-ceeec190f3bc
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-05T08:28:19+02:00'
            elementCondition: null
            fieldUid: 1d65442c-c0b9-46f4-8518-9a6c53e21bc1 # Featured Image
            handle: null
            includeInCards: false
            instructions: null
            label: 'Default Featured Image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3adb9569-f9be-4f86-9a6c-2df3d6816874
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 44927ccf-a678-414e-bd93-d96a5fd71966
        userCondition: null
handle: siteInfo
hasTitleField: false
icon: gear
name: 'Site Info - Global Settings'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
