color: null
fieldLayouts:
  6e414421-9c51-4c18-ae15-b858843720ed:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-20T19:11:39+02:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: aa92f6bc-6f7a-4a15-b60c-3a82cb0b15a4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-20T19:11:39+02:00'
            elementCondition: null
            fieldUid: 86b9888e-ef59-4f68-8ece-9b7badf30277 # Multi Line Text
            handle: text
            includeInCards: true
            instructions: null
            label: __blank__
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 93d9ef91-67bb-4ce6-b86b-d446e05d5b85
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: cb85e172-be3d-443c-8def-36bee1a8c4a6
        userCondition: null
handle: text
hasTitleField: false
icon: paragraph
name: Text
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
