color: null
fieldLayouts:
  f9fd81a3-4c7a-4d24-a9dd-f2d098212e18:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-05T08:28:19+02:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 57df947f-e2a1-49bb-a720-6a6039674589
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-05T08:28:19+02:00'
            elementCondition: null
            fieldUid: 1d65442c-c0b9-46f4-8518-9a6c53e21bc1 # Featured Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 36fe213d-2fc9-40c5-83c9-f5886a477658
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-05T08:28:19+02:00'
            dismissible: true
            elementCondition: null
            style: tip
            tip: 'Topics will be displayed here'
            type: craft\fieldlayoutelements\Tip
            uid: f5314ca9-ae20-4021-ac27-ac75a28421db
            userCondition: null
        name: Content
        uid: 454d69aa-b602-415e-916a-3fcea836674e
        userCondition: null
handle: topicIndex
hasTitleField: true
icon: tags
name: 'Topic Index'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: language
