color: null
fieldLayouts:
  c52db41b-4b4c-4a3b-8461-51c077a891c2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-07T12:02:47+02:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 99f3bd93-4f00-4211-97a6-3a55e6737b18
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-07T12:02:47+02:00'
            elementCondition: null
            template: _cp/related-entries
            type: craft\fieldlayoutelements\Template
            uid: 4bef2a63-0220-47bb-ace3-24018bba6227
            userCondition: null
            width: 100
        name: Content
        uid: 64c79e4b-d52e-4b8f-901e-1ea7ec1149d0
        userCondition: null
handle: topic
hasTitleField: true
icon: tag
name: Topic
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: language
