color: blue
fieldLayouts:
  d24c2f3d-3e8b-4557-8be7-8997a801ea28:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-12T09:35:29+02:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: be2b9b90-1cdc-4bcd-9965-15e494314721
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-12T09:35:29+02:00'
            elementCondition: null
            fieldUid: 763955f3-df9e-4052-ac07-2ac51d4cf621 # Column Wrapper Left
            handle: null
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 06b43f6b-bce2-479f-af02-30a9d5495f34
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-09-12T09:35:29+02:00'
            elementCondition: null
            fieldUid: d5adf46d-5753-4fad-9646-825eb5702f7b # Column Wrapper Right
            handle: null
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 47899d39-dbc6-40b4-b2b8-ecc70f78b86b
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: b470ea7a-f77f-42cd-ade9-16ae81be0254
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-12T09:35:29+02:00'
            elementCondition: null
            fieldUid: 23ea6fd1-e412-40c0-9c01-d18acd9094c3 # Column Span
            handle: null
            includeInCards: false
            instructions: null
            label: 'Span of first Column'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6e8c4df9-3e8b-4fcd-8325-2f9ee246472e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-12T09:35:29+02:00'
            elementCondition: null
            fieldUid: 731cc91d-5ec7-402d-8517-f00dcfd831d6 # Block Width
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 89c20b2b-11df-4f16-af7f-0fa94e637252
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-12T09:35:29+02:00'
            elementCondition: null
            fieldUid: e4c5d3c4-17ab-43a4-b29c-85a19e1992d2 # Background Color
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 94a59f2f-a8d1-4279-9103-17061a069579
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-12T09:35:29+02:00'
            elementCondition: null
            fieldUid: e4fb909a-1304-48ce-8fff-3b71f3a0275d # Background Color Width
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ae7b1b9f-cfd1-43c1-82e8-c7affe57e7c2
            userCondition: null
            warning: null
            width: 100
        name: Style
        uid: bd250ae9-b161-4c52-a7d0-2f134408abb3
        userCondition: null
handle: twoColumns
hasTitleField: false
icon: table-columns
name: 'Two Columns'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
