altTranslationKeyFormat: null
altTranslationMethod: language
fieldLayouts:
  a9d58556-baca-4c30-916a-bef0d1ee1f14:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-10T09:52:13+02:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: be381213-38ff-4fec-a714-0d5578979925
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            dateAdded: '2024-08-10T09:52:13+02:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: true
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: e4045d2e-d485-4bc3-8f3f-170aab9924a2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-10T09:52:13+02:00'
            elementCondition: null
            fieldUid: 560e7c36-f763-440f-b9b5-1d87228bc6df # Untranslatable Short Text
            handle: copyright
            includeInCards: true
            instructions: null
            label: Copyright
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 230731e5-bcd8-4470-b580-6f1577e6f6fc
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-10T09:52:13+02:00'
            elementCondition: null
            template: _cp/related-entries
            type: craft\fieldlayoutelements\Template
            uid: fc9151dc-3a9e-4b69-b85f-243107885e1d
            userCondition: null
            width: 100
        name: Content
        uid: c1e3a4d5-1e1c-4d1a-990f-39e3b823150c
        userCondition: null
fs: volumesFs
handle: images
name: Images
sortOrder: 1
subpath: images
titleTranslationKeyFormat: null
titleTranslationMethod: language
transformFs: transformFs
transformSubpath: images
