columnSuffix: null
handle: bodyContent
instructions: null
name: 'Body Content'
searchable: true
settings:
  createButtonLabel: 'New content block'
  entryTypes:
    - a3605555-7165-4ea9-a338-870db2eba7ca # Heading
    - 78f9590c-8302-4bbc-8e62-39e3f6a2bd57 # Text
    - a33610ee-ece8-47a1-949e-94477da5fd4d # Image
    - 19d8011f-2129-4d06-b597-49d7125063c7 # Quote
    - b8b190d9-515e-4173-a718-1c221741d34c # Links
    - ae1983cd-1a96-4f39-8b1d-fae967428550 # Infobox
    - 3cd3265b-7102-49ff-9823-f3c237cc0b39 # Accordion
    - 9128a883-c73e-4009-b8d5-7971ce954682 # Special
    - 2cea504e-140d-4a1e-8821-171a99ebe4c4 # Two Columns
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  siteSettings:
    __assoc__:
      -
        - 2393c71c-94e8-4e90-bb19-949696b8be0b # English
        -
          __assoc__:
            -
              - uriFormat
              - '{owner.uri}/content/{id}'
            -
              - template
              - _entries/content
      -
        - b7acd2cf-9449-4637-a40c-2e266a19cc19 # Deutsch
        -
          __assoc__:
            -
              - uriFormat
              - '{owner.uri}/content/{id}'
            -
              - template
              - _entries/content
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
