columnSuffix: null
handle: columnContentLeft
instructions: null
name: 'Column Content Left'
searchable: true
settings:
  createButtonLabel: 'New content block in left column'
  entryTypes:
    - a3605555-7165-4ea9-a338-870db2eba7ca # Heading
    - 78f9590c-8302-4bbc-8e62-39e3f6a2bd57 # Text
    - a33610ee-ece8-47a1-949e-94477da5fd4d # Image
    - 19d8011f-2129-4d06-b597-49d7125063c7 # Quote
    - b8b190d9-515e-4173-a718-1c221741d34c # Links
    - ae1983cd-1a96-4f39-8b1d-fae967428550 # Infobox
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
