columnSuffix: null
handle: image
instructions: 'At least 768px wide. For best result, use 1000px min. if the wide style is used.'
name: Image
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  branchLimit: null
  defaultUploadLocationSource: 'volume:c9a4fbad-6ca0-4e20-ba72-da2c14a38190' # Images
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  previewMode: thumbs
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:c9a4fbad-6ca0-4e20-ba72-da2c14a38190' # Images
  restrictedLocationSubpath: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Asset
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\assets\AssetCondition
      -
        - conditionRules
        -
          -
            __assoc__:
              -
                - class
                - craft\elements\conditions\assets\WidthConditionRule
              -
                - uid
                - 73c6baec-2203-47fa-bee7-633be75c6120
              -
                - operator
                - '>='
              -
                - value
                - '768'
              -
                - maxValue
                - ''
  selectionLabel: 'Select an image'
  showCardsInGrid: true
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:c9a4fbad-6ca0-4e20-ba72-da2c14a38190' # Images
  targetSiteId: null
  validateRelatedElements: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
