columnSuffix: null
handle: topics
instructions: null
name: Topics
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: 'Add a topic'
  showCardsInGrid: false
  showSiteMenu: false
  sources:
    - 'section:4e30878f-1e26-4e1b-9ced-b3cd32686df9' # Topic
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
